#!/bin/bash

# Control script for appletv. Sends remote commands to Apple TV 
# via LIRC and the commandir repeater. 

push_button () {
    commandir_send_lirc appletv $1;
}

case "$1" in
    play)
	push_button "PLAY";
	;;
    menu)
	push_button "MENU";
	;;
    ok)
	push_button "OK";
	;;
    up)
	push_button "UP";
	;;
    down)
	push_button "DOWN";
	;;
    left)
	push_button "LEFT";
	;;
    right)
	push_button "RIGHT";
	;;
    *)
	echo "Unsupported command '$1'. Valid commands are : 'up','down','left','right','play','menu','ok'.";
	exit 1;
	;;
esac;
