#!/bin/bash

# from_appletv  - Commands to switch from AppleTV to PC input.

# Hitting 'Menu' will stop any playing that is happening on the AppleTV. 
# This is where a 'stop' button would be nice...
appletv menu;

# Switch input back to MythTV
hdmi_switch mythtv;

killall irexec
