#!/bin/bash

# Control script for teh HDMI switch. Sends remote commands to the switch 
# via LIRC and the commandir repeater. 

# Port on the HDMI switch to which the Myth box is connected. 
MYTH_PORT=BTN_3

# Port on the HDMI switch to which Apple TV is connected. 
APPLETV_PORT=BTN_2

switch_to () {
    commandir_send_lirc hdmi_switch $1;
}

case "$1" in
    appletv)
	switch_to $APPLETV_PORT;
	;;
    mythtv)
	switch_to $MYTH_PORT;
	;;
    *)
	echo "Unsupported command '$1'. Valid options are: 'appletv', 'mythtv'.";
	exit 1;
	;;
esac;

	